aws_profile: genai
last_action_type: paper
last_directory: /Users/leonvaness/Desktop/TecRacer Dokumente
last_language: en-US
output_lines: 10
output_path: /Users/leonvaness/Desktop/TecRacer Dokumente/result_7-9.txt
s3_bucket: audionote-lvaness
